Module7 task2
htmlacademy-javascript/1416813-kekstagram-23 pull request #6
Opened 2021-06-22 10:46 UTC by Borisova-EV

2021-06-23 11:31 UTC, Manyaka requested changes

2021-06-24 09:46 UTC, Borisova-EV commented on js/create-gallery-photos.js
> +    closeBigPhoto();
Создаем DOM-узел, и сразу навешиваем на него обработчик. Если сделать уже после добавления всего фрагмента в разметку пришлось бы снова находить эти элементы и через цикл перебирать и добавлять обработчик событий. Ну или делегировать родителю(но я это только вчера узнала, 8 лайв посмотрела))

2021-06-24 09:56 UTC, Manyaka commented on js/create-gallery-photos.js
> +    closeBigPhoto();
Это ты про 21 строку рассказываешь. А в 23 у тебя чего?

2021-06-24 14:32 UTC, Manyaka requested changes

2021-06-24 14:32 UTC, Manyaka commented on js/create-big-photo.js
> +function showBigPicture(pictures) {
```suggestion
function showBigPicture(picture) {
```
как тут количество картинок внезапно стало во множественном числе, тогда как ты передаешь в обработчик одну единственную картинку - ту, на которой кликнули

2021-06-24 14:32 UTC, Manyaka commented on js/create-big-photo.js
> +  commentsLoader.classList.add('hidden');
смотри, ты тут что-то делаешь с коментами (кроме 68 строки) - не удобнее было бы это вынести в отдельную функцию, тк иначе название ф-и showBigPicture - не соотв её содержимому

2021-06-24 14:32 UTC, Manyaka commented on js/create-big-photo.js
> +export { bigPictureContainer, showBigPicture };
ты нигде не используешь экспортируемую переменную bigPictureContainer

2021-06-24 14:32 UTC, Manyaka commented on js/close-big-photo.js
> +}
когда ты закрываешь биг фото - эти слушатели уже не нужны, надо их ремувить

2021-06-24 14:32 UTC, Manyaka commented on js/close-big-photo.js
> +
ну и неаккуратно - чего за дырка то

2021-06-25 08:17 UTC, Borisova-EV commented on js/create-big-photo.js
> +  commentsLoader.classList.add('hidden');
Может тогда функцию переименовать? showBigPhotoPopup ? Просто у меня уже есть функция добавления описания одного комментария и функция добавления всех видимых комментариев. А в showBigPhoto я просто вызываю эти функции и временно скрываю загрузку новых комментариев и счетчик комментарием( в дз сказано, что с ними будем позже разбираться). Ну и удаляю прошлые комментарии.

2021-06-25 08:20 UTC, Manyaka commented on js/create-big-photo.js
> +  commentsLoader.classList.add('hidden');
странно, в модули ты можешь по одной функции вынести, а тут не видишь? тут 2 функции - одна связана с действием с коментами, а вторая showBigPicture - функцию, связанную с коментами как есть - кроме 68 строки, копируешь в другую функцию, называешь еще Работа с коментами - и вызываешь последнюю в шоу биг пикче - и смотришь - хорошо получилось или нет

2021-06-29 12:27 UTC, Manyaka requested changes

2021-06-29 12:27 UTC, Manyaka commented on js/close-big-photo.js
> +};
https://up.htmlacademy.ru/javascript/23/criteries#d5

> Все функции объявлены единообразно.

2021-06-29 12:27 UTC, Manyaka commented on js/close-big-photo.js
> +};
и остальные поправь

2021-06-29 12:27 UTC, Manyaka commented on js/close-big-photo.js
> +  document.addEventListener('keydown', keyDownEsc);
```suggestion
  document.addEventListener('keydown', documentKeydownHadler);
  или
  document.addEventListener('keydown', onDocumentKeydown);
```

https://up.htmlacademy.ru/javascript/23/criteries#d4

> Из названия обработчика события и функции-колбэка следует, что это обработчик.

выбери как тебе нравится называть, через хендлер или через он и так всё и называй

2021-06-29 12:27 UTC, Manyaka commented on js/close-big-photo.js
> +  document.addEventListener('keydown', keyDownEsc);
все остальные поправь

2021-06-29 12:27 UTC, Manyaka commented on js/create-big-photo.js
> +  user.height = '35';
магические значения

2021-06-29 12:27 UTC, Manyaka commented on js/create-big-photo.js
> +  const commentAmount = (amount >= 5) ? 5 : amount;
магические значения

2021-06-29 12:27 UTC, Manyaka commented on js/utils.js
> +}
чёто у меня эта функция под вопросом. Посмотри, не нарушает ли она критерий: https://up.htmlacademy.ru/javascript/23/criteries#b25

> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM.

Так как думаешь?

2021-07-01 09:55 UTC, Borisova-EV commented on js/utils.js
> +}
Как мне кажется, в критерии говорится что сначала нужно полностью создать элемент со всеми классами атрибутами, а потом уже добавлять в DOM-дерево. А в этой функции мы ничего никуда не добавляем, просто создаем элемент

2021-07-01 16:09 UTC, merged