Module8 task1
htmlacademy-javascript/1416813-kekstagram-23 pull request #7
Opened 2021-07-05 09:36 UTC by Borisova-EV

2021-07-06 06:28 UTC, Manyaka requested changes

2021-07-06 06:28 UTC, Manyaka commented on js/form.js
> +  document.addEventListener('keydown', onEditPopupEscKeyDown);
```suggestion
  document.addEventListener('keydown', onDocumentKeydown);
```

2021-07-06 06:28 UTC, Manyaka commented on js/form.js
> +});
функцию отдельно вынеси, тк это функция валидации

2021-07-06 06:28 UTC, Manyaka commented on js/form.js
> +  }
тоже функция валидации !== это не функция-обработчик события

2021-07-06 09:14 UTC, Borisova-EV commented on js/form.js
> +  document.addEventListener('keydown', onEditPopupEscKeyDown);
У нас есть два окна (большое фото и форма редактирования). Получается, что так надо назвать обе функции, а они разные. Поэтому у меня onBigPhotoPopupEscKeyDown и onEditPopupEscKeyDown

2021-07-06 09:16 UTC, Manyaka commented on js/form.js
> +  document.addEventListener('keydown', onEditPopupEscKeyDown);
внезапно, тогда это не разные функции, а одна и та же

2021-07-06 09:17 UTC, Manyaka commented on js/form.js
> +  document.addEventListener('keydown', onEditPopupEscKeyDown);
и проверь в рамках одного модуля они или в разных?

2021-07-06 09:18 UTC, Borisova-EV commented on js/form.js
> +});
Я правильно понимаю все условия нужно вынести в отельную функция и вызвать ее в обработчике?

2021-07-06 09:21 UTC, Manyaka commented on js/form.js
> +});
да

2021-07-06 09:24 UTC, Borisova-EV commented on js/form.js
> +  document.addEventListener('keydown', onEditPopupEscKeyDown);
Они в разных модулях, но они вызывают разные функции закрытия. Можно эту функцию кинуть в модуль вспомогательных функций, а функцию закрытия передавать в качестве аргумента?

2021-07-06 09:26 UTC, Manyaka commented on js/form.js
> +  document.addEventListener('keydown', onEditPopupEscKeyDown);
ну если они в разных - то какое главное правило модуля?

2021-07-06 09:31 UTC, Borisova-EV commented on js/form.js
> +  document.addEventListener('keydown', onEditPopupEscKeyDown);
Независимость от других модулей?) т.е. можно называть одинаково?)

2021-07-06 18:15 UTC, Manyaka requested changes

2021-07-06 18:15 UTC, Manyaka commented on js/validation-hash-tags.js
> +  return duplicates.length >= 1;
```suggestion
  return duplicates.length > 0;
```
как думаешь так сработает?

2021-07-06 18:15 UTC, Manyaka commented on js/form.js
> +});
прочитай про https://developer.mozilla.org/ru/docs/Web/API/Document/activeElement - это всё-таки будет более буллетпрувный вариант

2021-07-07 03:54 UTC, Borisova-EV commented on js/validation-hash-tags.js
> +  return duplicates.length >= 1;
Да)

2021-07-08 10:44 UTC, Manyaka requested changes

2021-07-09 06:42 UTC, Manyaka commented on js/utils.js
> +const onDocumentKeyDown = (evt, closePopup) => {
В общем, удобнее всё же тебе не выносить эту функцию в утилиты, пока, а вызывать её в своих модулях, тк у тебя разный колбек там вызывается.

2021-07-09 06:43 UTC, Manyaka commented on js/utils.js
> +const onDocumentKeyDown = (evt, closePopup) => {
я всё же предлагаю не передавать сюда колбек, а сделать функцию обработчик события onDocumentKeydown - локально в своем модуле

2021-07-09 06:44 UTC, Manyaka commented on js/utils.js
> +    closePopup();
а место проверки элемента в фокусе не изменится

2021-07-11 09:05 UTC, Borisova-EV commented on js/utils.js
> +    closePopup();
Последний комментарий не поняла. Сделала в onDocumentKeydown дополнительную проверку, чтобы фокусированным элементом было не поле с хэштегом или комментариями. Но все равно обработчик работает.

2021-07-11 09:54 UTC, Borisova-EV commented on js/utils.js
> +    evt.preventDefault();
На лайве говорилось, что может быть какое-то действие навешано на клавишу по умолчанию, поэтому надо удалять его.

2021-07-13 04:38 UTC, merged