Module9 task1
htmlacademy-javascript/1416813-kekstagram-23 pull request #9
Opened 2021-07-18 17:10 UTC by Borisova-EV

2021-07-19 17:12 UTC, Manyaka requested changes

2021-07-19 17:12 UTC, Manyaka commented on js/main.js
>  const photos = createPhotos();
файл change-effect.js - 55 строка: const updateSlider = (minValue, maxValue, stepValue) - можешь спкойно писать min, max, step - это понятно внутри модуля

а можешь даже пойти дальше и попробовать использовать деструктуризацию, тут удобно её попробовать. Передать в функцию updateSlider(options) (да тут потащим всё, как с ивентом, но потом, благодаря деструктуризации джс всё порежет) - а принять const updateSlider = ({ min, max, step })

2021-07-19 17:12 UTC, Manyaka commented on js/main.js
>  const photos = createPhotos();
файл change-effect.js - 67 строка const changeLevelEffect - не хочешь тут попробовать switch? Будет по красивее код

2021-07-20 11:35 UTC, Borisova-EV commented on js/main.js
> файл loader-comments.js - 30 строка - createCommentsUser - forUser maybe? И кстати у юзера может быть несколько коментов?

я имела в виду, создание комментариев пользователей. Исправила на createUserComments может так понятней

2021-07-20 14:04 UTC, Borisova-EV commented on js/main.js
>  const photos = createPhotos();
> файл change-scale.js
> 
> > Кроме визуального применения эффекта необходимо записывать значение в скрытое поле для дальнейшей отправки на сервер.
> 
> это не реализовано

Есть changeValueInputScale

2021-07-20 14:16 UTC, Borisova-EV commented on js/main.js
>  const photos = createPhotos();
> ![Снимок экрана 2021-07-19 в 19 57 51](https://user-images.githubusercontent.com/6417966/126198169-28e69ea3-4723-471c-bbbb-56fe0787edad.jpg)
> 
> > Обратите внимание, что при переключении фильтра, уровень эффекта должен сразу сбрасываться до начального состояния
> 
> поправить

При переключении эффектов, уровень насыщенности сбрасывается до начального значения (100%). Это из ТЗ. Так у меня так и есть, или ты про что-то другое

2021-07-20 14:21 UTC, Borisova-EV commented on js/main.js
>  const photos = createPhotos();
> файл change-effect.js - 94 строка, если тебе нужно только валью - evt.target.value - то лучше его и передавай в эту функцию, чего весь ивент то тягать :)

Что тут не соображу как это сделать

2021-07-20 16:42 UTC, Manyaka requested changes

2021-07-20 16:42 UTC, Manyaka commented on index.html
>    <link rel="stylesheet" href="css/normalize.css">
не, нормалайз идет первым, тк он нормализует стили. Потом всякие цсс-ки сторонних библиотек, для того, чтобы ты могла их кастомизировать, если нужно, а потом твои стили.

2021-07-20 16:42 UTC, Manyaka commented on index.html
> +          <div class="social__comment-count"><span class="social__comment-count--loaded">5 </span>из <span
не, это же не модификатор social__comment-count, это тоже элемент блока social. Так что как-нибудь `social__loaded-comment-count` можно назвать.

2021-07-20 16:42 UTC, Manyaka commented on js/form.js
> +const inputScaleValue = uploadPictureForm.querySelector('.scale__control--value');
это же просто инпут, а не инпут-валью, из-за этого получается такой код: ` inputScaleValue.value =` валью-валью :(

2021-07-20 16:42 UTC, Manyaka commented on js/form.js
> +    changeEffectPhoto(evt);
```suggestion
    changeEffectPhoto(evt.target.value);
```

https://github.com/htmlacademy-javascript/1416813-kekstagram-23/pull/9#discussion_r673169443

2021-07-21 05:23 UTC, merged